[package]
name = "combat"
version = "0.1.0"
authors = ["arthexis <arthexis@gmail.com>"]

[dependencies]
dice-roller = "0.1.3"
clap = "2.33.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
